// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBwdzAbPqjaZ3o8XK0ZyymyEDk4eNjTCNc',
    appId: '1:100214415027:web:951f477d72ba4ecc18dac6',
    messagingSenderId: '100214415027',
    projectId: 'lateral-goods-433801-a0',
    authDomain: 'lateral-goods-433801-a0.firebaseapp.com',
    storageBucket: 'lateral-goods-433801-a0.firebasestorage.app',
    measurementId: 'G-NRN2SDGQ9Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBlrR-3q4UXKJlxe5cOm720ySO4-sc2BrY',
    appId: '1:100214415027:android:7fa7d38f9029384018dac6',
    messagingSenderId: '100214415027',
    projectId: 'lateral-goods-433801-a0',
    storageBucket: 'lateral-goods-433801-a0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAwmF9_FRgLftg5mQ1Zh6NZH9UD4OhwS8Q',
    appId: '1:100214415027:ios:a0bcbf2b18dc6c2218dac6',
    messagingSenderId: '100214415027',
    projectId: 'lateral-goods-433801-a0',
    storageBucket: 'lateral-goods-433801-a0.firebasestorage.app',
    iosBundleId: 'com.example.testFlutter4',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAwmF9_FRgLftg5mQ1Zh6NZH9UD4OhwS8Q',
    appId: '1:100214415027:ios:a0bcbf2b18dc6c2218dac6',
    messagingSenderId: '100214415027',
    projectId: 'lateral-goods-433801-a0',
    storageBucket: 'lateral-goods-433801-a0.firebasestorage.app',
    iosBundleId: 'com.example.testFlutter4',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBwdzAbPqjaZ3o8XK0ZyymyEDk4eNjTCNc',
    appId: '1:100214415027:web:83e99d9ba3b4723518dac6',
    messagingSenderId: '100214415027',
    projectId: 'lateral-goods-433801-a0',
    authDomain: 'lateral-goods-433801-a0.firebaseapp.com',
    storageBucket: 'lateral-goods-433801-a0.firebasestorage.app',
    measurementId: 'G-QDDCFHV2J8',
  );
}
